name: Cl

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download Chrome Remote Desktop Host DEB
      run: wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb

    - name: Install Chrome Remote Desktop Host
      run: |
        sudo apt-get update
        sudo apt-get install --assume-yes ./chrome-remote-desktop_current_amd64.deb

    - name: Set up Chrome Remote Desktop with PIN
      run: |
        {
          echo 123456
          echo 123456
        } | DISPLAY= /opt/google/chrome-remote-desktop/start-host --code="4/0AdLIrYdkHd-8ku69yZcFxIDakKY-HAii3p40CHIkDdxuRpWoCwcDk8lanJpKp0KdovqNuA" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname)
