name: Set up Chrome Remote Desktop on Ubuntu

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up environment variables
      run: |
        echo "USERNAME_CHROME=user" >> $GITHUB_ENV
        echo "PASSWORD_CHROME=123456" >> $GITHUB_ENV
        echo "PIN=123456" >> $GITHUB_ENV
        echo "CHROME_REMOTE_DESKTOP_URL=https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb" >> $GITHUB_ENV
        echo "FIREFOX_ESR_PACKAGE=firefox-esr" >> $GITHUB_ENV

    - name: Update and upgrade system packages
      run: sudo apt-get update && sudo apt-get upgrade -y

    - name: Create user for Chrome Remote Desktop
      run: |
        sudo useradd -m $USERNAME_CHROME
        echo "$USERNAME_CHROME:$PASSWORD_CHROME" | sudo chpasswd
        sudo sed -i 's/\/bin\/sh/\/bin\/bash/g' /etc/passwd

    - name: Install Chrome Remote Desktop
      run: |
        wget -q --show-progress $CHROME_REMOTE_DESKTOP_URL
        sudo dpkg --install $(basename $CHROME_REMOTE_DESKTOP_URL) || sudo apt-get install --fix-broken -y
        rm $(basename $CHROME_REMOTE_DESKTOP_URL)

    - name: Clean up Chrome Remote Desktop installation files
      run: rm -rf $(basename $CHROME_REMOTE_DESKTOP_URL)

    - name: Install XFCE desktop environment
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes -y xfce4 desktop-base dbus-x11 xscreensaver

    - name: Set up Chrome Remote Desktop session
      run: |
        echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" | sudo tee /etc/chrome-remote-desktop-session

    - name: Install Firefox ESR
      run: |
        sudo add-apt-repository -y ppa:mozillateam/ppa
        sudo apt-get update
        sudo apt-get install -y $FIREFOX_ESR_PACKAGE

    - name: Install recommended XFCE software and tools
      run: |
        sudo apt-get install -y software-properties-common thunar-archive-plugin thunar-media-tags-plugin xarchiver unzip rar gnome-terminal

    - name: Clean up
      run: |
        sudo apt-get autoremove -y
        sudo apt-get autoclean -y

    - name: Set up Chrome Remote Desktop with PIN
      run: |
        {
          echo $PIN
          echo $PIN
        } | sudo /opt/google/chrome-remote-desktop/start-host --code="4/4/0AdLIrYdHhVk7d9pK5YVkhxifXS2KSpTdixfbvdIAH8ACJ_W8jEGg2g2dZo_loWgcc492RQ" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$(hostname) --user-name=$USERNAME_CHROME

    - name: Continuous Run
      run: |
        while true; do
          echo "Continuous running..."
          # Add your commands here
          sleep 120
        done
